### ISSUE TITLE
Repository '@io_bazel_rules_kotlin_configured' is not defined

### ISSUE THREAD

**Issue by luxe** [Tinder/bazel-diff#157]
Using commit f6014ee4681af397d581a35d48bc71a15f9aac69, and using the example from the readme:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "bazel_diff",
  urls = [
        "RELEASE_ARCHIVE_URL",
    ],
    sha256 = "UPDATE_ME",
    strip_prefix = "UPDATE_ME"
)

load("@bazel_diff//:repositories.bzl", "bazel_diff_dependencies")

bazel_diff_dependencies()

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@bazel_diff//:artifacts.bzl", "BAZEL_DIFF_MAVEN_ARTIFACTS")

maven_install(
    name = "bazel_diff_maven",
    artifacts = BAZEL_DIFF_MAVEN_ARTIFACTS,
    repositories = [
        "http://uk.maven.org/maven2",
        "https://jcenter.bintray.com/",
    ],
)
```

I get the following error with `bazel run @bazel_diff//:bazel-diff -- bazel-diff -h`:

```
ERROR: /home/luxe/.cache/bazel/_bazel_luxe/9b1d289b10540c9752c68b55618a2156/external/bazel_diff/BUILD:1:6:  
error loading package '@bazel_diff//cli': at /home/luxe/.cache/bazel/_bazel_luxe/9b1d289b10540c9752c68b55618a2156/external/io_bazel_rules_kotlin/kotlin/jvm.bzl:9:5:  
at /home/luxe/.cache/bazel/_bazel_luxe/9b1d289b10540c9752c68b55618a2156/external/io_bazel_rules_kotlin/kotlin/internal/opts.bzl:22:5:  
Unable to find package for @io_bazel_rules_kotlin_configured//jvm:opts.bzl: The repository '@io_bazel_rules_kotlin_configured' could not be resolved: Repository '@io_bazel_rules_kotlin_configured' is not defined. 
and referenced by '@bazel_diff//:bazel-diff'
```

**Comment by tinder-maxwellelliott** [comment]
This should be resolved as of https://github.com/Tinder/bazel-diff/pull/158

**Comment by jmthvt** [comment]
I'm can't still reproduce with the latest bazel-diff 4.3.0 release.

**Comment by tinder-maxwellelliott** [comment]
I just merged this which validates that the example script can run https://github.com/Tinder/bazel-diff/pull/162

**Comment by jmthvt** [comment]
As far as I understand, the test script builds bazel-diff within the workspace.

Can you reproduce this when building bazel-diff from another project though, as documented here https://github.com/Tinder/bazel-diff#build-from-source-in-your-bazel-project?

It looks like in that precise case the kotlin rules fails to init. The way this rule tries to setup `io_bazel_rules_kotlin_configured` doesn't seem to play nice with an external project.

**Comment by tinder-maxwellelliott** [comment]
Can we test with this change? https://github.com/Tinder/bazel-diff/pull/163. I think this is just a setup issue.

**Comment by jmthvt** [comment]
Configured as per the readme:

`ERROR: Error computing the main repository mapping: cannot load '//:repositories.bzl': no such file`

Reverting `load("//:repositories.bzl", "bazel_diff_dependencies")` to `load("@bazel_diff//:repositories.bzl", "bazel_diff_dependencies")`:

```
ERROR: Error computing the main repository mapping: Every .bzl file must have a corresponding package, but '@bazel_diff//:repositories.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

Makes sense, the jar likely doesn't contain this target.
After restoring the http_archive:

```
ERROR: Traceback (most recent call last):
	File "/home/jmthvt/repos/REDACTED/WORKSPACE", line 617, column 20, in <toplevel>
		kotlin_repositories()
	File "/home/jmthvt/.cache/bazel/_bazel_jmthvt/2299fc45cf64d298be53c0b783603165/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
		rules_repository(
Error in repository_rule: invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
ERROR: Error computing the main repository mapping: at /home/jmthvt/.cache/bazel/_bazel_jmthvt/2299fc45cf64d298be53c0b783603165/external/io_bazel_rules_kotlin/kotlin/core.bzl:2:5: at /home/jmthvt/.cache/bazel/_bazel_jmthvt/2299fc45cf64d298be53c0b783603165/external/io_bazel_rules_kotlin/kotlin/internal/opts.bzl:16:5: Encountered error while reading extension file 'kotlin/opts.bzl': no such package '@io_bazel_rules_kotlin_configured//kotlin': error loading package 'external': Could not load //external package
```

That looks like the same error we were getting originally, however this surfaces the potential root cause. There's a related open issue on rules_kotlin: https://github.com/bazelbuild/rules_kotlin/issues/883

I would suggest to revert https://github.com/Tinder/bazel-diff/pull/163, the configs looked good to me: we do not want to setup `rules_kotlin` on the root project, since bazel-diff does it on its own workspace. We also need the `http_archive` in order to build from another project.

**Comment by tinder-maxwellelliott** [comment]
Looks like we just have to hope **rules_kotlin** fixes this, otherwise the fix is to use a version lower than Bazel 6. We could rewrite everything to a different language to avoid this issue, but that has its own complexities
